const citiesData = [
    { city: "Mumbai", country: "India", currency: "INR", symbol: "₹" },
    { city: "Delhi", country: "India", currency: "INR", symbol: "₹" },
    { city: "Bangalore", country: "India", currency: "INR", symbol: "₹" },
    { city: "Hyderabad", country: "India", currency: "INR", symbol: "₹" },
    { city: "Ahmedabad", country: "India", currency: "INR", symbol: "₹" },
    { city: "Chennai", country: "India", currency: "INR", symbol: "₹" },
    { city: "Kolkata", country: "India", currency: "INR", symbol: "₹" },
    { city: "Surat", country: "India", currency: "INR", symbol: "₹" },
    { city: "Pune", country: "India", currency: "INR", symbol: "₹" },
    { city: "Jaipur", country: "India", currency: "INR", symbol: "₹" },
    { city: "New York", country: "USA", currency: "USD", symbol: "$" },
    { city: "Los Angeles", country: "USA", currency: "USD", symbol: "$" },
    { city: "Chicago", country: "USA", currency: "USD", symbol: "$" },
    { city: "Houston", country: "USA", currency: "USD", symbol: "$" },
    { city: "Phoenix", country: "USA", currency: "USD", symbol: "$" },
    { city: "Philadelphia", country: "USA", currency: "USD", symbol: "$" },
    { city: "San Antonio", country: "USA", currency: "USD", symbol: "$" },
    { city: "San Diego", country: "USA", currency: "USD", symbol: "$" },
    { city: "Dallas", country: "USA", currency: "USD", symbol: "$" },
    { city: "San Jose", country: "USA", currency: "USD", symbol: "$" },
    { city: "Austin", country: "USA", currency: "USD", symbol: "$" },
    { city: "London", country: "UK", currency: "GBP", symbol: "£" },
    { city: "Birmingham", country: "UK", currency: "GBP", symbol: "£" },
    { city: "Manchester", country: "UK", currency: "GBP", symbol: "£" },
    { city: "Glasgow", country: "UK", currency: "GBP", symbol: "£" },
    { city: "Liverpool", country: "UK", currency: "GBP", symbol: "£" },
    { city: "Leeds", country: "UK", currency: "GBP", symbol: "£" },
    { city: "Tokyo", country: "Japan", currency: "JPY", symbol: "¥" },
    { city: "Yokohama", country: "Japan", currency: "JPY", symbol: "¥" },
    { city: "Osaka", country: "Japan", currency: "JPY", symbol: "¥" },
    { city: "Nagoya", country: "Japan", currency: "JPY", symbol: "¥" },
    { city: "Sapporo", country: "Japan", currency: "JPY", symbol: "¥" },
    { city: "Paris", country: "France", currency: "EUR", symbol: "€" },
    { city: "Marseille", country: "France", currency: "EUR", symbol: "€" },
    { city: "Lyon", country: "France", currency: "EUR", symbol: "€" },
    { city: "Toulouse", country: "France", currency: "EUR", symbol: "€" },
    { city: "Berlin", country: "Germany", currency: "EUR", symbol: "€" },
    { city: "Hamburg", country: "Germany", currency: "EUR", symbol: "€" },
    { city: "Munich", country: "Germany", currency: "EUR", symbol: "€" },
    { city: "Cologne", country: "Germany", currency: "EUR", symbol: "€" },
    { city: "Frankfurt", country: "Germany", currency: "EUR", symbol: "€" },
    { city: "Beijing", country: "China", currency: "CNY", symbol: "¥" },
    { city: "Shanghai", country: "China", currency: "CNY", symbol: "¥" },
    { city: "Guangzhou", country: "China", currency: "CNY", symbol: "¥" },
    { city: "Shenzhen", country: "China", currency: "CNY", symbol: "¥" },
    { city: "Chongqing", country: "China", currency: "CNY", symbol: "¥" },
    { city: "Moscow", country: "Russia", currency: "RUB", symbol: "₽" },
    { city: "Saint Petersburg", country: "Russia", currency: "RUB", symbol: "₽" },
    { city: "Novosibirsk", country: "Russia", currency: "RUB", symbol: "₽" },
    { city: "Yekaterinburg", country: "Russia", currency: "RUB", symbol: "₽" },
    { city: "Sao Paulo", country: "Brazil", currency: "BRL", symbol: "R$" },
    { city: "Rio de Janeiro", country: "Brazil", currency: "BRL", symbol: "R$" },
    { city: "Brasilia", country: "Brazil", currency: "BRL", symbol: "R$" },
    { city: "Salvador", country: "Brazil", currency: "BRL", symbol: "R$" },
    { city: "Sydney", country: "Australia", currency: "AUD", symbol: "A$" },
    { city: "Melbourne", country: "Australia", currency: "AUD", symbol: "A$" },
    { city: "Brisbane", country: "Australia", currency: "AUD", symbol: "A$" },
    { city: "Perth", country: "Australia", currency: "AUD", symbol: "A$" },
    { city: "Toronto", country: "Canada", currency: "CAD", symbol: "C$" },
    { city: "Montreal", country: "Canada", currency: "CAD", symbol: "C$" },
    { city: "Vancouver", country: "Canada", currency: "CAD", symbol: "C$" },
    { city: "Ottawa", country: "Canada", currency: "CAD", symbol: "C$" },
    { city: "Dubai", country: "UAE", currency: "AED", symbol: "د.إ" },
    { city: "Abu Dhabi", country: "UAE", currency: "AED", symbol: "د.إ" },
    { city: "Sharjah", country: "UAE", currency: "AED", symbol: "د.إ" },
    { city: "Singapore", country: "Singapore", currency: "SGD", symbol: "S$" },
    { city: "Hong Kong", country: "Hong Kong", currency: "HKD", symbol: "HK$" },
    { city: "Seoul", country: "South Korea", currency: "KRW", symbol: "₩" },
    { city: "Busan", country: "South Korea", currency: "KRW", symbol: "₩" },
    { city: "Incheon", country: "South Korea", currency: "KRW", symbol: "₩" },
    { city: "Bangkok", country: "Thailand", currency: "THB", symbol: "฿" },
    { city: "Nonthaburi", country: "Thailand", currency: "THB", symbol: "฿" },
    { city: "Jakarta", country: "Indonesia", currency: "IDR", symbol: "Rp" },
    { city: "Surabaya", country: "Indonesia", currency: "IDR", symbol: "Rp" },
    { city: "Bandung", country: "Indonesia", currency: "IDR", symbol: "Rp" },
    { city: "Kuala Lumpur", country: "Malaysia", currency: "MYR", symbol: "RM" },
    { city: "George Town", country: "Malaysia", currency: "MYR", symbol: "RM" },
    { city: "Manila", country: "Philippines", currency: "PHP", symbol: "₱" },
    { city: "Quezon City", country: "Philippines", currency: "PHP", symbol: "₱" },
    { city: "Davao City", country: "Philippines", currency: "PHP", symbol: "₱" },
    { city: "Ho Chi Minh City", country: "Vietnam", currency: "VND", symbol: "₫" },
    { city: "Hanoi", country: "Vietnam", currency: "VND", symbol: "₫" },
    { city: "Istanbul", country: "Turkey", currency: "TRY", symbol: "₺" },
    { city: "Ankara", country: "Turkey", currency: "TRY", symbol: "₺" },
    { city: "Izmir", country: "Turkey", currency: "TRY", symbol: "₺" },
    { city: "Riyadh", country: "Saudi Arabia", currency: "SAR", symbol: "﷼" },
    { city: "Jeddah", country: "Saudi Arabia", currency: "SAR", symbol: "﷼" },
    { city: "Mecca", country: "Saudi Arabia", currency: "SAR", symbol: "﷼" },
    { city: "Cairo", country: "Egypt", currency: "EGP", symbol: "E£" },
    { city: "Alexandria", country: "Egypt", currency: "EGP", symbol: "E£" },
    { city: "Giza", country: "Egypt", currency: "EGP", symbol: "E£" },
    { city: "Lagos", country: "Nigeria", currency: "NGN", symbol: "₦" },
    { city: "Kano", country: "Nigeria", currency: "NGN", symbol: "₦" },
    { city: "Ibadan", country: "Nigeria", currency: "NGN", symbol: "₦" },
    { city: "Johannesburg", country: "South Africa", currency: "ZAR", symbol: "R" },
    { city: "Cape Town", country: "South Africa", currency: "ZAR", symbol: "R" },
    { city: "Durban", country: "South Africa", currency: "ZAR", symbol: "R" },
    { city: "Nairobi", country: "Kenya", currency: "KES", symbol: "KSh" },
    { city: "Mombasa", country: "Kenya", currency: "KES", symbol: "KSh" },
    { city: "Casablanca", country: "Morocco", currency: "MAD", symbol: "د.م." },
    { city: "Rabat", country: "Morocco", currency: "MAD", symbol: "د.م." },
    { city: "Buenos Aires", country: "Argentina", currency: "ARS", symbol: "$" },
    { city: "Cordoba", country: "Argentina", currency: "ARS", symbol: "$" },
    { city: "Rosario", country: "Argentina", currency: "ARS", symbol: "$" },
    { city: "Mexico City", country: "Mexico", currency: "MXN", symbol: "$" },
    { city: "Ecatepec", country: "Mexico", currency: "MXN", symbol: "$" },
    { city: "Guadalajara", country: "Mexico", currency: "MXN", symbol: "$" },
    { city: "Madrid", country: "Spain", currency: "EUR", symbol: "€" },
    { city: "Barcelona", country: "Spain", currency: "EUR", symbol: "€" },
    { city: "Valencia", country: "Spain", currency: "EUR", symbol: "€" },
    { city: "Rome", country: "Italy", currency: "EUR", symbol: "€" },
    { city: "Milan", country: "Italy", currency: "EUR", symbol: "€" },
    { city: "Naples", country: "Italy", currency: "EUR", symbol: "€" },
    { city: "Amsterdam", country: "Netherlands", currency: "EUR", symbol: "€" },
    { city: "Rotterdam", country: "Netherlands", currency: "EUR", symbol: "€" },
    { city: "Brussels", country: "Belgium", currency: "EUR", symbol: "€" },
    { city: "Vienna", country: "Austria", currency: "EUR", symbol: "€" },
    { city: "Zurich", country: "Switzerland", currency: "CHF", symbol: "CHF" },
    { city: "Geneva", country: "Switzerland", currency: "CHF", symbol: "CHF" },
    { city: "Stockholm", country: "Sweden", currency: "SEK", symbol: "kr" },
    { city: "Oslo", country: "Norway", currency: "NOK", symbol: "kr" },
    { city: "Copenhagen", country: "Denmark", currency: "DKK", symbol: "kr" },
    { city: "Helsinki", country: "Finland", currency: "EUR", symbol: "€" },
    { city: "Athens", country: "Greece", currency: "EUR", symbol: "€" },
    { city: "Lisbon", country: "Portugal", currency: "EUR", symbol: "€" },
    { city: "Dublin", country: "Ireland", currency: "EUR", symbol: "€" },
    { city: "Prague", country: "Czech Republic", currency: "CZK", symbol: "Kč" },
    { city: "Warsaw", country: "Poland", currency: "PLN", symbol: "zł" },
    { city: "Budapest", country: "Hungary", currency: "HUF", symbol: "Ft" },
    { city: "Bucharest", country: "Romania", currency: "RON", symbol: "lei" },
    { city: "Kyiv", country: "Ukraine", currency: "UAH", symbol: "₴" },
    { city: "Tel Aviv", country: "Israel", currency: "ILS", symbol: "₪" },
    { city: "Jerusalem", country: "Israel", currency: "ILS", symbol: "₪" },
    { city: "Tehran", country: "Iran", currency: "IRR", symbol: "﷼" },
    { city: "Baghdad", country: "Iraq", currency: "IQD", symbol: "ع.د" },
    { city: "Doha", country: "Qatar", currency: "QAR", symbol: "﷼" },
    { city: "Kuwait City", country: "Kuwait", currency: "KWD", symbol: "د.ك" },
    { city: "Muscat", country: "Oman", currency: "OMR", symbol: "﷼" },
    { city: "Amman", country: "Jordan", currency: "JOD", symbol: "د.ا" },
    { city: "Beirut", country: "Lebanon", currency: "LBP", symbol: "ل.ل" },
    { city: "Santiago", country: "Chile", currency: "CLP", symbol: "$" },
    { city: "Lima", country: "Peru", currency: "PEN", symbol: "S/." },
    { city: "Bogota", country: "Colombia", currency: "COP", symbol: "$" },
    { city: "Caracas", country: "Venezuela", currency: "VES", symbol: "Bs." },
    { city: "Quito", country: "Ecuador", currency: "USD", symbol: "$" },
    { city: "Montevideo", country: "Uruguay", currency: "UYU", symbol: "$U" },
    { city: "Asuncion", country: "Paraguay", currency: "PYG", symbol: "₲" },
    { city: "La Paz", country: "Bolivia", currency: "BOB", symbol: "Bs." },
    { city: "Panama City", country: "Panama", currency: "PAB", symbol: "B/." },
    { city: "San Jose", country: "Costa Rica", currency: "CRC", symbol: "₡" },
    { city: "Guatemala City", country: "Guatemala", currency: "GTQ", symbol: "Q" },
    { city: "San Salvador", country: "El Salvador", currency: "USD", symbol: "$" },
    { city: "Tegucigalpa", country: "Honduras", currency: "HNL", symbol: "L" },
    { city: "Managua", country: "Nicaragua", currency: "NIO", symbol: "C$" },
    { city: "Havana", country: "Cuba", currency: "CUP", symbol: "$" },
    { city: "Santo Domingo", country: "Dominican Republic", currency: "DOP", symbol: "RD$" },
    { city: "Port-au-Prince", country: "Haiti", currency: "HTG", symbol: "G" },
    { city: "Kingston", country: "Jamaica", currency: "JMD", symbol: "J$" },
    { city: "Nassau", country: "Bahamas", currency: "BSD", symbol: "B$" }
];
